language: android

env:
  global:
  - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
licenses:
- 'android-sdk-license-.+'
- 'android-sdk-preview-license-.+'
- 'google-gdk-license-.+'

before_install:
- yes | sdkmanager "build-tools;28.0.2"

before_script:
- echo "apiKey=temporary_key" > teamwork-api.properties

script:
- ./gradlew build checkstyle ktlint test